# Generated by Django 4.1.7 on 2023-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapasapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=300)),
                ("Password", models.CharField(max_length=30)),
            ],
        ),
    ]
