# Generated by Django 4.1.7 on 2023-04-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapasapp", "0002_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dish",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
